name:                functor-combinators
version:             0.4.0.0
github:              "mstksg/functor-combinators"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Tools for functor combinator-based program design
category:            Data

description: |
    Tools for working with /functor combinators/: types that take functors (or
    other indexed types) and returns a new functor that "enhances" or "mixes"
    them in some way.  In the process, you can design featureful programs by
    composing smaller "primitives" using basic unversal combinators.

    The main entry point is "Data.Functor.Combinators", but more fine-grained
    functionality and extra combinators (some of them re-implementations for
    compatibility) are available in other modules as well.

    This library does not define new functor combinators for the most part,
    but rather re-exports them from different parts of the Haskell ecosystem
    and provides a uniform interface.

    See the README for a quick overview, and also
    <https://blog.jle.im/entry/functor-combinatorpedia.html> for an in-depth
    dive into the motivation behind functor combinator-driven development,
    examples of the functor combinators in this library, and details about how
    to use these abstractions!

tested-with: GHC >= 8.6

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- PatternSynonyms
- QuantifiedConstraints
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeInType
- TypeOperators
- UndecidableInstances
- UndecidableSuperClasses
- ViewPatterns

dependencies:
- base >= 4.12 && < 5
- bifunctors
- free
- nonempty-containers
- semigroupoids
- transformers
- trivial-constraint >= 0.5

library:
  source-dirs: src
  other-modules:
  - Data.HFunctor.Internal
  - Data.HFunctor.Chain.Internal
  - Data.HBifunctor.Tensor.Internal
  dependencies:
  - StateVar
  - assoc
  - comonad
  - constraints
  - containers
  - contravariant
  - deriving-compat
  - hashable
  - invariant
  - kan-extensions
  - mmorph
  - mtl
  - natural-transformation
  - pointed
  - profunctors
  - sop-core
  - tagged
  - these
  - unordered-containers
  - vinyl

tests:
  functor-combinators-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dependent-sum
    - functor-combinators
    - hedgehog >= 0.6
    - tasty
    - tasty-hedgehog
